aliases:
 - &filter-only-master
   branches:
     only:
       - master

version: 2
jobs:
  deploy-website:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "nadeemkhedr@users.noreply.github.com"
            git config --global user.name "Nadeem Khedr"
            echo "machine github.com login nadeemkhedr password $GITHUB_TOKEN" > ~/.netrc
            cd website && npm install && GIT_USER=nadeemkhedr npm run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
         filters: *filter-only-master
